apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: camunda
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
      - image: camunda/camunda-bpm-platform:latest
        name: camunda	
